### ISSUE TITLE
[Feature Request] Code folding based on `DocumentSymbol`

### ISSUE THREAD

**Issue by Gravifer** [kenkangxgwe/vscode-lsp-wl#7]
The currently available `outline` feature has been a great help for package development, however it would still be nice if code folding in the editor, based on the [document structure](https://github.com/kenkangxgwe/vscode-lsp-wl#user-content-language-server-features:~:text=DocumentSymbol,-You) could be implemented. 

The [related APIs](https://code.visualstudio.com/api/references/vscode-api#1220:~:text=FoldingRangeProvider%23,extensions%20and%20Folding%20in%20the%20editor.) could aid this purpose.

**Comment by kenkangxgwe** [comment]
This should have been implemented by https://github.com/kenkangxgwe/lsp-wl/commit/cc6370475f4d15eeac012864b8778d8c3bd03199. If you wanna try it immediately, you can checkout the `develop` branch in lsp-wl, otherwise, you can wait a short while for the `master` branch to be updated. Thanks for the feature request.
